### ISSUE TITLE
urllib2.HTTPError: HTTP Error 503: Service Unavailable while using translate() from textblob

### ISSUE THREAD

**Issue by valmikadik** [sloria/TextBlob#138]
from textblob import TextBlob
text="Wi-Fi Direct"
tb=TextBlob(text)
translated_string=tb.translate(to='en')

**Error**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\textblob\blob.py", line 505, in translate
    from_lang=from_lang, to_lang=to))
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 52, in transl
ate
    response = self._request(self.url, host=host, type_=type_, data=data)
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 92, in _reque
st
    resp = request.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by sloria** [comment]
This was reported in #137 . Let's continue discussion there.
