### ISSUE TITLE
HTTP Error 503: Service Unavailable for blob.translate()

### ISSUE THREAD

**Issue by poolebu** [sloria/TextBlob#241]
Hello, 

I just started with this awesome tool, I just got this error and was working fine 1 hour ago, so I wanted to report it:

```python
>>> from textblob import TextBlob
>>> text = '''
... The titular threat of The Blob has always struck me as the ultimate movie
... monster: an insatiably hungry, amoeba-like mass able to penetrate
... virtually any safeguard, capable of--as a doomed doctor chillingly
... describes it--"assimilating flesh on contact.
... Snide comparisons to gelatin be damned, it's a concept with the most
... devastating of potential consequences, not unlike the grey goo scenario
... proposed by technological theorists fearful of
... artificial intelligence run rampant.
... '''
>>> blob = TextBlob(text)
>>> blob.translate(to="es")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/textblob/blob.py", line 541, in translate
    from_lang=from_lang, to_lang=to))
  File "/usr/local/lib/python3.6/site-packages/textblob/translate.py", line 54, in translate
    response = self._request(url, host=host, type_=type_, data=data)
  File "/usr/local/lib/python3.6/site-packages/textblob/translate.py", line 92, in _request
    resp = request.urlopen(req)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by sloria** [comment]
This is the same issue as #215 . I've update that issue's title to reflect that this is happening in `translate()`.
