### ISSUE TITLE
I get this error even though PositiveNaiveBayesClassifier is present in classifier.py

### ISSUE THREAD

**Issue by iamnewspecies** [sloria/TextBlob#58]
Traceback (most recent call last):
  File "/home/newspecies/Documents/Projects/final_year_project/scripts/audio_input.py", line 1, in <module>
    from textblob.classifiers import NaiveBayesClassifier
  File "/usr/local/lib/python2.7/dist-packages/textblob-0.8.4-py2.7.egg/textblob/classifiers.py", line 359, in <module>
    class PositiveNaiveBayesClassifier(NLTKClassifier):
  File "/usr/local/lib/python2.7/dist-packages/textblob-0.8.4-py2.7.egg/textblob/classifiers.py", line 400, in PositiveNaiveBayesClassifier
    nltk_class = nltk.classify.PositiveNaiveBayesClassifier
AttributeError: 'module' object has no attribute 'PositiveNaiveBayesClassifier'

**Comment by chandra589** [comment]
I am not able to upgrade nltk using $ pip install --upgrade nltk, is there any other way to upgrade nltk.
