### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by canivel** [sloria/TextBlob#62]
Installation goes ok, but when I try to import the error shows up ... appear to me that is not compatible with my numpy, which is working normal for everything else.

what should I do?
Thanks

> > > import textblob
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/textblob/**init**.py", line 9, in <module>
> > >     from .blob import TextBlob, Word, Sentence, Blobber, WordList
> > >   File "/Library/Python/2.7/site-packages/textblob/blob.py", line 28, in <module>
> > >     from textblob.packages import nltk
> > >   File "/Library/Python/2.7/site-packages/textblob/packages.py", line 12, in <module>
> > >     import nltk
> > >   File "/Library/Python/2.7/site-packages/nltk/**init**.py", line 105, in <module>
> > >     from collocations import *
> > >   File "/Library/Python/2.7/site-packages/nltk/collocations.py", line 38, in <module>
> > >     from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
> > >   File "/Library/Python/2.7/site-packages/nltk/metrics/**init**.py", line 16, in <module>
> > >     from nltk.metrics.scores import          (accuracy, precision, recall, f_measure,
> > >   File "/Library/Python/2.7/site-packages/nltk/metrics/scores.py", line 16, in <module>
> > >     from scipy.stats.stats import betai
> > >   File "/Library/Python/2.7/site-packages/scipy-0.14.0.dev_7cefb25-py2.7-macosx-10.9-intel.egg/scipy/stats/**init**.py", line 330, in <module>
> > >     from .stats import *
> > >   File "/Library/Python/2.7/site-packages/scipy-0.14.0.dev_7cefb25-py2.7-macosx-10.9-intel.egg/scipy/stats/stats.py", line 181, in <module>
> > >     import scipy.special as special
> > >   File "/Library/Python/2.7/site-packages/scipy-0.14.0.dev_7cefb25-py2.7-macosx-10.9-intel.egg/scipy/special/**init**.py", line 546, in <module>
> > >     from ._ufuncs import *
> > >   File "__init__.pxd", line 155, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:21372)
> > > ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by shubham2706** [comment]
I am also getting an error like this. I have tried uninstalling textblob, numpy and scipy and then installed them back using pip in the below order
scipy -> numpy -> textblob
Any suggestions? 

>> import textblob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/textblob/__init__.py", line 9, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "/Library/Python/2.7/site-packages/textblob/blob.py", line 28, in <module>
    import nltk
  File "/Library/Python/2.7/site-packages/nltk/__init__.py", line 117, in <module>
    from nltk.align import *
  File "/Library/Python/2.7/site-packages/nltk/align/__init__.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "/Library/Python/2.7/site-packages/nltk/align/ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "/Library/Python/2.7/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/__init__.py", line 59, in <module>
    from nltk.corpus.reader.tagged import *
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/tagged.py", line 17, in <module>
    from nltk.tag import str2tuple, map_tag
  File "/Library/Python/2.7/site-packages/nltk/tag/__init__.py", line 65, in <module>
    from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
  File "/Library/Python/2.7/site-packages/nltk/tag/sequential.py", line 25, in <module>
    from nltk.classify.naivebayes import NaiveBayesClassifier
  File "/Library/Python/2.7/site-packages/nltk/classify/__init__.py", line 93, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/Library/Python/2.7/site-packages/nltk/classify/scikitlearn.py", line 41, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/Library/Python/2.7/site-packages/sklearn/feature_extraction/__init__.py", line 7, in <module>
    from .dict_vectorizer import DictVectorizer
  File "/Library/Python/2.7/site-packages/sklearn/feature_extraction/dict_vectorizer.py", line 14, in <module>
    from ..utils import atleast2d_or_csr, tosequence
  File "/Library/Python/2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by shubham2706** [comment]
Never mind. It's running smoothly now. pip uninstall scikit-learn and install it back.

**Comment by jkmiao** [comment]
sudo pip uninstall numpy
sudo pip uninstall pandas

sudo pip install numpy
sudo pip install pandas
