### ISSUE TITLE
detect language results in http server error:

### ISSUE THREAD

**Issue by coolsubbu** [sloria/TextBlob#69]
the following happens for words with single and double character

> > > y=TextBlob("um")
> > > y.detect_language()

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    y.detect_language()
  File "C:\Python27\lib\site-packages\textblob\blob.py", line 529, in detect_language
    return self.translator.detect(self.raw)
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 57, in detect
    json5 = self._get_json5(self.url, host=host, type_=type_, data=data)
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 83, in _get_json5
    r = request.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 442, in error
    result = self._call_chain(_args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "C:\Python27\lib\urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by bigstem** [comment]
I tried textblob-0.11.1.dist-info but 

from textblob.blob import TextBlob
blob = TextBlob('wait')
print(blob.detect_language()) 
gives me HTTPError: HTTP Error 503: Service Unavailable

and I see that translate.py uses url = http://translate.google.com/translate_a/t
translate.py(92) this fails  resp = request.urlopen(req)


The only issue which I am unable to figure out is when I use the url directly I get response.
Here is the code
(Pdb) import requests
(Pdb) url = 'http://translate.google.com/translate_a/t'
(Pdb) print(requests.get(url, params=data).content)
["wait","en"]
