### ISSUE TITLE
HTTP Error 503: Service Unavailible translate()

### ISSUE THREAD

**Issue by minuscorp** [sloria/TextBlob#74]
Hello.

I've got an application which extracts Spanish Tweets and I'm using the translate method to get this text into English and get the sentiment analysis, unavailible in Spanish yet.

I had no problems at all in all the time I've used it, but when I looked today, I got the next traceback on the Celery task which does the translation and sentiment:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "C:\Python27\lib\site-packages\celery\app\trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\Users\bisite-dev\Documents\Visual Studio 2013\Projects\web\web\gui\tasks.py", line 127, in sentiment_analysis
    comment.add_atribute("sentiment", text_analyzer.analyze_sentiment(comment.atributos['original_text']))
  File "C:\Users\bisite-dev\Documents\Visual Studio 2013\Projects\web\web\libraries\TextAnalyzer.py", line 18, in analyze_sentiment
    for sentence in blob.translate(from_lang='es', to='en').sentences:
  File "C:\Python27\lib\site-packages\textblob\blob.py", line 509, in translate
    from_lang=from_lang, to_lang=to))
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 51, in translate
    json5 = self._get_json5(self.url, host=host, type_=type_, data=data)
  File "C:\Python27\lib\site-packages\textblob\translate.py", line 87, in _get_json5
    resp = request.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

This never happened before and I was afraid it was a IP ban, but from the same computer where I'm executing the task, if I make the GET, I recieve a correct answer from Google API.
I tried to copy the user-agent string from the library to use the newer Chrome ones but I recieve the same 503 error.

What ideas do you have?

**Comment by sloria** [comment]
I have not been able to reproduce this. Are you still seeing this error, or can this be closed?

**Comment by sloria** [comment]
Closing this for now.

**Comment by TriRpi** [comment]
I have the same issue. Probably because of googles api not being free anymore.
