### ISSUE TITLE
unable to use it in django

### ISSUE THREAD

**Issue by a134man** [sloria/TextBlob#94]
I am trying to use it in my django project for text classification. I already have the latest version of it's corpora. Still, I get the error: MissingCorpusError at /

To download the necessary data, simply run

```
python -m textblob.download_corpora
```

Any help??

**Comment by sloria** [comment]
This is unlikely to be a django-related issue.  What error do you get when downloading the corpora? Also,  what version of textblob and nltk is installed?

**Comment by a134man** [comment]
i do not get any error in development server of django. But on apache, i get this error

**Comment by ysolis** [comment]
1. We asume that you download the corpora.
2. You use different users to run in dev server in django and apache ? if this is the case you need to re-dowload the corpora for the user in web server apache, are you using fastcgi, mod_wcgi to run the webapp in Apache ?

**Comment by jschnurr** [comment]
Confirm the data exists, and is accessible by the user running the code. The error message will tell you where to look:
```bash
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  Searched in:
    - '/home/jschnurr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/home/jschnurr/.virtualenvs/textblob94/nltk_data'
    - '/home/jschnurr/.virtualenvs/textblob94/lib/nltk_data'
    - u''
**********************************************************************

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    blob.tags           # [('The', 'DT'), ('titular', 'JJ'),
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/decorators.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/blob.py", line 475, in pos_tags
    return [val for sublist in [s.pos_tags for s in self.sentences] for val in sublist]
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/decorators.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/blob.py", line 630, in sentences
    return self._create_sentence_objects()
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/blob.py", line 674, in _create_sentence_objects
    sentences = sent_tokenize(self.raw)
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/base.py", line 64, in itokenize
    return (t for t in self.tokenize(text, *args, **kwargs))
  File "/home/jschnurr/.virtualenvs/textblob94/local/lib/python2.7/site-packages/textblob/decorators.py", line 38, in decorated
    raise MissingCorpusError()
textblob.exceptions.MissingCorpusError: 
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.
```
Closing for inactivity.
