### ISSUE TITLE
Not working in python3.2.3

### ISSUE THREAD

**Issue by dmartincc** [sloria/TextBlob#98]
When running text blob in a virtualenv with python version 3.2.3, it shows up the following SyntaxError, 
```
(euler)david@datum:~/euler$ python -m textblob.download_corpora
Traceback (most recent call last):
  File "/usr/lib/python3.2/runpy.py", line 140, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python3.2/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python3.2/pkgutil.py", line 461, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python3.2/pkgutil.py", line 471, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python3.2/pkgutil.py", line 427, in iter_importers
    __import__(pkg)
  File "/home/david/.virtualenvs/euler/lib/python3.2/site-packages/textblob/__init__.py", line 9, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "/home/david/.virtualenvs/euler/lib/python3.2/site-packages/textblob/blob.py", line 32, in <module>
    from textblob.inflect import singularize as _singularize, pluralize as _pluralize
  File "/home/david/.virtualenvs/euler/lib/python3.2/site-packages/textblob/inflect.py", line 12, in <module>
    from textblob.en.inflect import singularize, pluralize
  File "/home/david/.virtualenvs/euler/lib/python3.2/site-packages/textblob/en/__init__.py", line 8, in <module>
    from textblob._text import (Parser as _Parser, Sentiment as _Sentiment, Lexicon,
  File "/home/david/.virtualenvs/euler/lib/python3.2/site-packages/textblob/_text.py", line 313
    and tokens[j] in ("'", "\"", u"”", u"’", "...", ".", "!", "?", ")", EOS):
                                      ^
SyntaxError: invalid syntax
```

**Comment by sloria** [comment]
TextBlob does not support Python versions less than 3.3.
